apiVersion: v1
kind: Service
metadata:
  name: premier-league-app-service
  namespace: default
spec:
  selector:
    app: premier-league-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort